### BuildDwelling
@gameId = scenario-3
@playerId = player-3
@dwellingId = dwelling-5

### BuildDwelling
PUT http://localhost:8080/games/{{gameId}}/dwellings/{{dwellingId}}
Content-Type: application/json
X-Player-Id: {{playerId}}

{
  "creatureId": "angel",
  "costPerTroop": {
    "gold": 3000,
    "gems": 1
  }
}

### IncreaseAvailableCreatures
PUT http://localhost:8080/games/{{gameId}}/dwellings/{{dwellingId}}/available-creatures-increases
Content-Type: application/json
X-Player-Id: {{playerId}}

{
  "creatureId": "angel",
  "increaseBy": 1
}

### RecruitCreature
PUT http://localhost:8080/games/{{gameId}}/dwellings/{{dwellingId}}/creature-recruitments
Content-Type: application/json
X-Player-Id: {{playerId}}

{
  "creatureId": "angel",
  "armyId": "army-1",
  "quantity": 3,
  "expectedCost": {
    "gold": 9000,
    "gems": 3
  }
}

### Dwelling read model
GET http://localhost:8080/games/{{gameId}}/dwellings/{{dwellingId}}
Content-Type: application/json

